/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class LoginDetailsSet extends javax.swing.JFrame {

    /**
     * Creates new form LoginDetailsSet
     */
    
    public static int memberID = 0;
    public static String memberName =null;
    public static String role =null;
    
    public LoginDetailsSet() {
        initComponents();

        con =DBconnect.Connect();    
        
        lblLabirarianID.setText(Integer.toString(memberID));
        lblLabirarianName.setText(memberName);
        
        checkPreviousPass();
        
        
    }
    
    
    Connection con=null;
    PreparedStatement pst;
    ResultSet rs;
    
    public boolean checkPreviousPass(){
        boolean status=false;
       
        try {
            pst = con.prepareStatement("select username, password from login where  ID=? and role=?");
            pst.setInt(1, memberID);
            pst.setString(2, role);
            
            rs = pst.executeQuery();
            
            if(rs.next() == false){
                btnUpdateUP.setEnabled(false);
            }else{
                btnAddUP.setEnabled(false);
                
                do{
                txtUserNameMember.setText(rs.getString("username"));
                txtPasswordMember.setText(rs.getString("password"));
                }while(rs.next());
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginDetailsSet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return status;   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddUP = new javax.swing.JButton();
        btnUpdateUP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUserNameMember = new javax.swing.JTextField();
        lblLabirarianID = new javax.swing.JLabel();
        lblLabirarianName = new javax.swing.JLabel();
        txtPasswordMember = new javax.swing.JPasswordField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddUP.setBackground(new java.awt.Color(204, 204, 204));
        btnAddUP.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddUP.setForeground(new java.awt.Color(0, 0, 0));
        btnAddUP.setText("Add");
        btnAddUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUPActionPerformed(evt);
            }
        });

        btnUpdateUP.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateUP.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnUpdateUP.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateUP.setText("Update");
        btnUpdateUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUPActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Member ID  :");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Name           :");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("User Name");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Password");

        txtUserNameMember.setBackground(new java.awt.Color(255, 255, 255));
        txtUserNameMember.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtUserNameMember.setForeground(new java.awt.Color(0, 0, 0));

        lblLabirarianID.setBackground(new java.awt.Color(255, 255, 255));
        lblLabirarianID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLabirarianID.setForeground(new java.awt.Color(0, 0, 0));
        lblLabirarianID.setText("-");

        lblLabirarianName.setBackground(new java.awt.Color(255, 255, 255));
        lblLabirarianName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLabirarianName.setForeground(new java.awt.Color(0, 0, 0));
        lblLabirarianName.setText("-");

        txtPasswordMember.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMember.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordMemberActionPerformed(evt);
            }
        });
        txtPasswordMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordMemberKeyPressed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 0, 0));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblLabirarianName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblLabirarianID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUserNameMember, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(txtPasswordMember)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btnUpdateUP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAddUP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblLabirarianID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblLabirarianName))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtUserNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPasswordMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUP)
                    .addComponent(btnAddUP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUPActionPerformed

        if(txtUserNameMember.getText().equals("") || txtPasswordMember.getPassword().equals("")){
             JOptionPane.showMessageDialog(null, "Enter Username and Password!", "Oops Wait...!", JOptionPane.ERROR_MESSAGE);
        }else{
            
    
            
            try {
                
                String username = txtUserNameMember.getText();
                String password = txtPasswordMember.getText();
                
                
                pst=con.prepareStatement("insert into Login(ID,role,username,password) value(?,?,?,?) ");
                pst.setInt(1, memberID);
                pst.setString(2, role);
                pst.setString(3, username);
                pst.setString(4,password);
                
               int k = pst.executeUpdate();
               if(k==1){
                   
                   txtUserNameMember.setText("");
                   txtPasswordMember.setText("");
                   
                   this.hide();
                   
                   JOptionPane.showMessageDialog(this,"Username Password Succesfully Set");
               }else{
                    JOptionPane.showMessageDialog(this,"Error:: Can't Add a new Username Password");
                   
                }
    
            } catch (SQLException ex) {
                Logger.getLogger(LoginDetailsSet.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
        
        
        
        
        //login.setVisible(true);
    }//GEN-LAST:event_btnAddUPActionPerformed

    private void btnUpdateUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUPActionPerformed
        // TODO add your handling code here:
        
        if(txtUserNameMember.getText().equals("") || txtPasswordMember.getPassword().equals("")){
             JOptionPane.showMessageDialog(null, "Enter Username and Password!", "Oops Wait...!", JOptionPane.ERROR_MESSAGE);
        }else{

            try {
                
                String username = txtUserNameMember.getText();
                String password = txtPasswordMember.getText();
                
                
                pst=con.prepareStatement("update Login set username =?,password = ?  where ID = ? and role = ? ");

                pst.setString(1, username);
                pst.setString(2,password);
                pst.setInt(3, memberID);
                pst.setString(4, role);
                
               int k = pst.executeUpdate();
               if(k==1){
                   
                   txtUserNameMember.setText("");
                   txtPasswordMember.setText("");
                   
                   this.hide();
                   
                   JOptionPane.showMessageDialog(this,"Username Password Succesfully Updated");
               }else{
                    JOptionPane.showMessageDialog(this,"Error:: Can't Update Username Password");
                   
                }
    
            } catch (SQLException ex) {
                Logger.getLogger(LoginDetailsSet.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
    }//GEN-LAST:event_btnUpdateUPActionPerformed

    private void txtPasswordMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMemberActionPerformed

    private void txtPasswordMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordMemberKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//
//            checklogin();
//        }
    }//GEN-LAST:event_txtPasswordMemberKeyPressed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        
        this.hide();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDetailsSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDetailsSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDetailsSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDetailsSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDetailsSet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUP;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdateUP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLabirarianID;
    private javax.swing.JLabel lblLabirarianName;
    private javax.swing.JPasswordField txtPasswordMember;
    private javax.swing.JTextField txtUserNameMember;
    // End of variables declaration//GEN-END:variables
}
